### ISSUE TITLE
Need Allow Input variable X from slider

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/DynamoWishlist#238] opened 2023-03-24 02:16 UTC
If this is an issue for Dynamo Core, please submit your issue on the [Dynamo Core issues page](https://github.com/DynamoDS/Dynamo/issues) or if this is an issue for Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a Wishlist request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## What improvement/feature would you like to see in Dynamo?
I want when I put x in slider, it will allow input x, because when I'm working with list count of another list, we don't have any way to continue.
![image](https://user-images.githubusercontent.com/31106432/227406298-3626ec2b-ea6b-4cf2-bccc-ab3ffa79e226.png)

## How would you see this improvement/feature working? 

if user don't input value is double like x, x variable will be to require from input of node
![image](https://user-images.githubusercontent.com/31106432/227407125-56de1315-d5dd-49ec-91e9-cbb2e93b4aa5.png)

## Please provide any sketch/mock-up or video of your requested improvement/feature

(Fill in here)

**Comment by Amoursol** [comment] 2023-03-24 14:05
@chuongmep could you please explain a little more where you want this to work? Inside Dynamo? Dynamo Player? Generative Design in Revit? 

The slightly tricky piece to this is if the latter two, you would need to "pre-run" the graph to have anything show up in this slider, unless content is serialized into it, which doesn't work in existing UI. This is the Data-Shapes approach of partial graph execution, decision to be made, then progressing through the graph.

**Comment by chuongmep** [comment] 2023-03-26 13:51
Hi @Amoursol , I belive this gif is clear for team 
![iShot_2023-03-26_21 49 31](https://user-images.githubusercontent.com/31106432/227780321-3b670121-3238-4950-b9b3-f08c92c9bb93.gif)

**Comment by andydandy74** [comment] 2023-03-26 14:43
Duplicate of #139 ?

**Comment by chuongmep** [comment] 2023-03-26 14:58
@andydandy74 Wow, I review and know that is correct what I want, now it has 9 year ago 😲

**Comment by chuongmep** [comment] 2023-03-26 15:05
Some guy also think about use for Generative Design before in forum : https://forum.dynamobim.com/t/celery-inputboundednumberslider-input/57118

**Comment by avidit** [comment] 2023-08-02 16:10
duplicate #139

**Closed** 2023-08-02 16:10 UTC
Labels: UX, Nodes, Dynamo Player
